# 监听端口
bind [::]:5053 -no-dualstack-selection -no-speed-check -no-cache

#### log ####
# 禁用日志
log-num 0

#### 缓存 ####
# 禁用缓存
cache-size 0

#### IPV6 #####
# 禁用双栈 IP 优选
dualstack-ip-selection no

#### 测速 ####
# 首次查询响应模式。模式：
#[first-ping]: 最快ping响应地址模式，DNS上游最快查询时延+ping时延最短，查询等待与链接体验最佳;
#[fastest-ip]: 最快IP地址模式，查询到的所有IP地址中ping最短的IP。需等待IP测速;
#[fastest-response]: 最快响应的DNS结果，DNS查询等待时间最短，返回的IP地址可能不是最快。
response-mode fastest-response

# 响应超时时间
server-timeout 5

#### 其它 ####
# 强制指定 qtype 返回 SOA。禁用 SOA 65
force-qtype-SOA 65
# TCP 链接空闲超时时间
tcp-idle-time 120

#### 上游 DNS 服务 ####
# 国内DNS
server-tls 119.28.28.28  -subnet 223.102.30.0/24
server-tls 180.76.76.76  -subnet 223.102.30.0/24
server-tls 223.6.6.6  -subnet 223.102.30.0/24
# 国外DNS
server-tls 1.0.0.1
server-tls 149.112.112.112
server-tls 8.8.4.4
